# Generated by Django 3.2.5 on 2021-07-23 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Memasik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memasik_category', to='MemApps.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('mem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MemApps.memasik')),
            ],
        ),
        migrations.CreateModel(
            name='Massege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massege', models.TextField()),
                ('date_time_massege', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemApps.user')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='memasik',
            field=models.ManyToManyField(to='MemApps.Memasik'),
        ),
    ]
